import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('api', {
  getProductByBarcode: (barcode: string, storeId: string) => ipcRenderer.invoke('get-product-by-barcode', barcode, storeId),
  getAllProducts: () => ipcRenderer.invoke('get-all-products'),
  saveManualProduct: (product: any) => ipcRenderer.invoke('save-manual-product', product),
  saveSale: (sale: any) => ipcRenderer.invoke('save-sale', sale),
  importXmlProducts: (xmlData: string, storeId: string) => ipcRenderer.invoke('import-xml-products', xmlData, storeId),
  getSyncStatus: () => ipcRenderer.invoke('get-sync-status'),
  getRepairs: () => ipcRenderer.invoke('get-repairs'),
  saveRepair: (repair: any) => ipcRenderer.invoke('save-repair', repair),
  updateRepairStatus: (data: {id: string, status: string, current_store_id: string}) => ipcRenderer.invoke('update-repair-status', data),
  uploadRepairImage: (data: {id: string, base64Data: string}) => ipcRenderer.invoke('upload-repair-image', data),
  downloadProtocolTemplate: () => ipcRenderer.invoke('download-protocol-template'),
  getStores: (includeArchived?: boolean) => ipcRenderer.invoke('get-stores', includeArchived),
  saveStore: (store: {id?: string, name: string}) => ipcRenderer.invoke('save-store', store),
  archiveStore: (data: {id: string, archived: boolean}) => ipcRenderer.invoke('archive-store', data),
  getUsers: () => ipcRenderer.invoke('get-users'),
  saveUser: (user: any) => ipcRenderer.invoke('save-user', user),
  login: (credentials: any) => ipcRenderer.invoke('login', credentials),
  getCommissions: () => ipcRenderer.invoke('get-commissions'),
  getDashboardStats: () => ipcRenderer.invoke('get-dashboard-stats'),
  getLowStockItems: () => ipcRenderer.invoke('get-low-stock-items'),
  getStaleStockItems: () => ipcRenderer.invoke('get-stale-stock-items'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings: {key: string, value: string}[]) => ipcRenderer.invoke('save-settings', settings),
  archiveProduct: (data: {id: string, archived: boolean}) => ipcRenderer.invoke('archive-product', data),
  updateInventoryQuantity: (data: {productId: string, store_id: string, quantity: number}) => ipcRenderer.invoke('update-inventory-quantity', data),
  uploadProductImage: (data: {barcode: string, base64Data: string}) => ipcRenderer.invoke('upload-product-image', data),
  isCloudConfigured: () => ipcRenderer.invoke('is-cloud-configured'),
  getAppTitle: () => ipcRenderer.invoke('get-app-title'),
  minimizeWindow: () => ipcRenderer.send('window-minimize'),
  maximizeWindow: () => ipcRenderer.send('window-maximize'),
  closeWindow: () => ipcRenderer.send('window-close'),
  });